{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rise-backend.fullname" . }}-secret
  labels:
    {{- include "rise-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-client-secret: {{ .Values.config.auth.clientSecret | quote }}
  database-password: {{ .Values.config.database.password | quote }}
  database-url: {{ include "rise-backend.databaseUrl" . | quote }}
{{- end }}
