{{- if and .Values.controllers.deployment.enabled (eq .Values.controllers.deployment.type "deployment-kubernetes") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rise.fullname" . }}
  labels:
    {{- include "rise.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rise.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "rise.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
