apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rise.fullname" . }}-config
  labels:
    {{- include "rise.labels" . | nindent 4 }}
data:
  # Production overrides from values.yaml
  # The image embeds /etc/rise/default.yaml at build time.
  production.yaml: |
{{ .Values.config | toYaml | nindent 4 }}
