apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rise.fullname" . }}-config
  labels:
    {{- include "rise.labels" . | nindent 4 }}
data:
  # A "production.yaml" already exists in the Rise image, so we use "local.yaml" only to override production
  # defaults.
  local.yaml: |
{{ .Values.config | toYaml | nindent 4 }}
