apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rise.fullname" . }}-config
  labels:
    {{- include "rise.labels" . | nindent 4 }}
data:
  # Local overrides from values.yaml
  local.yaml: |
{{ .Values.config | toYaml | nindent 4 }}
