apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rise.fullname" . }}-config
  labels:
    {{- include "rise.labels" . | nindent 4 }}
data:
  config.toml: |
{{ .Values.config | nindent 4 }}
