{{- if .Values.controllers.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rise.fullname" . }}-deployment-controller
  labels:
    {{- include "rise.labels" . | nindent 4 }}
    app.kubernetes.io/component: deployment-controller
spec:
  replicas: {{ .Values.controllers.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "rise.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: deployment-controller
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "rise.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: deployment-controller
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rise.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: deployment-controller
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: {{ include "rise.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "backend"
          - "controller"
          - "deployment-kubernetes"
        env:
        - name: RISE_CONFIG_DIR
          value: "/config"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "rise.fullname" .)) }}
              key: database-url
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: config
        configMap:
          name: {{ include "rise.fullname" . }}-config
      - name: tmp
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
