apiVersion: v1
kind: Service
metadata:
  name: {{ include "rise.fullname" . }}
  labels:
    {{- include "rise.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "rise.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
