apiVersion: v2
name: rise
description: A Helm chart for Rise - a Kubernetes deployment platform
type: application
version: 0.2.0
appVersion: "0.1.0"
keywords:
  - kubernetes
  - deployment
  - paas
home: https://github.com/niklasrosenstein/rise
sources:
  - https://github.com/niklasrosenstein/rise
